### ISSUE TITLE
when I use the version of svg.js V2, the latest version of svg.topath.js can't work well and report error;

### ISSUE THREAD

**Issue by tingshuai** [svgdotjs/svg.topath.js#10]
That's how I import the plugin :
`import '@svgdotjs/svg.topath.js'`
and that's the errors:
1.DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
2. Error in mounted hook: "InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name."
![7b493eed-69e6-4964-808e-3fcee217fa34 png](https://user-images.githubusercontent.com/23158246/51784342-1f884480-2182-11e9-967d-d7d3605c6cef.jpg)

**Comment by Fuzzyma** [comment]
The latest version ot svg.topath.js depends on svg.js v3.0.10. Even the latest commit messages states that:

> update plugin for use with svg.js v3

So please use the correct version
