### ISSUE TITLE
to path is not defined

### ISSUE THREAD

**Issue by thyash11** [svgdotjs/svg.topath.js#11]
Hi,

I have installed svg and to path plugin on my system, and created this html on root folder,

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SVG JS</title>
</head>
<body>
    <script src="node_modules/@svgdotjs/svg.js/dist/svg.js" charset="utf-8"></script>
    <script type="text/javascript">
        var canvas = SVG().addTo('body');
        var rect = canvas.rect(100, 200).attr({ rx: 10, ry: 5 });
        var rectPath = rect.toPath();
        alert(rectPath);
    </script>
</body>
</html>

Console says to path is not defined. I am new to npm and svg.js. Please help me on adding svgtopath plugin,

**Comment by Fuzzyma** [comment]
You didn't include the plugin with a script tag

**Comment by thyash11** [comment]
Thanks for quick reply. 

I guess there are two svg.topath.js files inside packpage.

for file inside spec folder, I got describe is not defined issue.
for file inside src folder, I got Unexpected token { issue.

So, I thought installing plugin will work itself.

Kindly, If there are any jsfiddle, so I can follow with it. 

Thanks in Advance :)

**Comment by Fuzzyma** [comment]
You can download the correct one on teh release page here: https://github.com/svgdotjs/svg.topath.js/releases/tag/2.0.2

for some reason, the actual distribution files arent uploaded to npm. We need to fix that. Try the above in the meantime
