### ISSUE TITLE
Implementation for text elements is missing

### ISSUE THREAD

**Issue by mIIrko** [svgdotjs/svg.topath.js#12]
> svg.topath.js to convert any other shape to a path

It seems "any" does not include the `text` element. I've tried to convert a text element but now I saw that this feature isn't implemented yet. Please update your (until that point really good) documentation..

**Comment by Fuzzyma** [comment]
To convert text you would need to have the font file because you need the path data for every glyph.

Imo this is pretty clear. However if you need to clarify that, feel free to submit a pr which I can merge
