### ISSUE TITLE
Text toPath

### ISSUE THREAD

**Issue by hassenc** [svgdotjs/svg.topath.js#2]
It seems that text elements cannot be converted to path yet. Do you plan to add this feature ?

**Comment by wm2zfei** [comment]
sample is not defined????

**Comment by wout** [comment]
@wm2zfei could you explain your question a bit more? And maybe open a new issue since this one is more than tree years old...

**Comment by kuzvac** [comment]
For converting text to Path you can use https://github.com/shrhdk/text-to-svg

**Comment by Fuzzyma** [comment]
or fontkit or opentype...

**Comment by kuzvac** [comment]
Yes, text-to-svg is based on opentype :)
