### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by IMPMAC** [svgdotjs/svg.topath.js#7]
Hi. I am trying to convert SVG shapes like rect, ellipse etc. to SVG paths. This is so I can do boolean operations on the resulting paths. 

I have the code:
` var mySVG = "<ellipse cx="0" cy="0" rx="66" ry="79.5" style="stroke: rgb(0,0,0); stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="translate(375.28 -54.22)"/>";
`

`
var draw = SVG('drawing');
`
`
var x = draw.svg(mySVG);
`
`
console.log(x.toPath());
`

After I do this operation, I get this error:

Uncaught ReferenceError: sample is not defined
    at create.toPath (svg.topath.js:159)

I am using svg.topath.js 0.4 with the latest version of the svg.js 

Do you know what I am doing wrong?

Many thanks

**Comment by Fuzzyma** [comment]
There is no version 0.4. Where did you find your lib?

**Comment by IMPMAC** [comment]
On this page
https://github.com/svgdotjs/svg.topath.js/blob/master/svg.topath.js

**Comment by Fuzzyma** [comment]
Try simply removing the `sample, ` and see if this works for you. Please report back!

**Comment by IMPMAC** [comment]
Removed that variable and it seems to be working now.

Now I just need to extract the d="..." from the result

**Comment by Fuzzyma** [comment]
well just do `el.toPath().attr('d')` or to have the path array `el.toPath().array()`
