### ISSUE TITLE
Cannot find name 'sample' at line 159

### ISSUE THREAD

**Issue by pycraft114** [svgdotjs/svg.topath.js#9]
<img width="428" alt="2018-05-29 2 23 33" src="https://user-images.githubusercontent.com/24728657/40639457-f928f2c0-634b-11e8-92fd-91905a953c94.png">
Cannot find name 'sample' at line 159

**Comment by derhuerst** [comment]
Please provide a full stack trace.

**Comment by Fuzzyma** [comment]
fixed with 2.0
